### ISSUE TITLE
edit readme to reflect new changes

### ISSUE THREAD

**Issue by tuxuday5** [tuxuday5/calc_tax_pnl_angel#3]
edit readme to reflect new changes

**Comment by pixobia** [comment]
can i add how to contribute this project in readme if so assign me this...

**Comment by tuxuday5** [comment]
[c9b6a7a](https://github.com/tuxuday5/calc_tax_pnl_angel/commit/c9b6a7a102edc2930dcccc2e3b51b3ac65217bce) i
